
  0%|                                                                                                                                         | 0/99 [00:00<?, ?it/s]
  0%|                                                                                                                                          | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/disi/NLU-exam-main/LM/part_1/main.py", line 70, in <module>
    main()
  File "/home/disi/NLU-exam-main/LM/part_1/main.py", line 64, in main
    run(train_raw, dev_raw, test_raw, lr=lr, runs=runs, epochs=epochs, clip=clip, patience=patience, device=device, hid_size=hid_size, emb_size=emb_size, model_type=model, optimizer_type=optimizer, use_dropout=use_dropout)
  File "/home/disi/NLU-exam-main/LM/part_1/functions.py", line 177, in run
    loss = train_loop(train_loader, optimizer, model, lang, criterion_train, clip=5)
  File "/home/disi/NLU-exam-main/LM/part_1/functions.py", line 39, in train_loop
    for sample in data:
  File "/home/disi/anaconda3/envs/nlu24/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/disi/anaconda3/envs/nlu24/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/disi/anaconda3/envs/nlu24/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/disi/NLU-exam-main/LM/part_1/utils.py", line 151, in collate_fn
    new_item["source"] = source.to(DEVICE)
NameError: name 'DEVICE' is not defined